# Use admin/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: backend-db
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_USER: admin
      MARIADB_PASSWORD: example
    volumes:
      - ./conf.d:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
    - "3306:3306"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
    mysql-data: {}