# Use admin/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: backend-db
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: admin
      MYSQL_PASSWORD: example
    volumes:
      - ./conf.d:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080